//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paricom.KGMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.jeesite.thinkgem.com/", ConfigurationName="KGMWebService.GmWebServlet")]
    public interface GmWebServlet {
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 jsonVlue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.saveSchedulingResponse saveScheduling(Paricom.KGMWebService.saveScheduling request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.loginResponse login(Paricom.KGMWebService.login request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.getVerifyCodeByContactsNameResponse getVerifyCodeByContactsName(Paricom.KGMWebService.getVerifyCodeByContactsName request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.saveCardNoResponse saveCardNo(Paricom.KGMWebService.saveCardNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.isExistOrderResponse isExistOrder(Paricom.KGMWebService.isExistOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        Paricom.KGMWebService.getCardNoByOrderResponse getCardNoByOrder(Paricom.KGMWebService.getCardNoByOrder request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveScheduling {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveScheduling", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.saveSchedulingBody Body;
        
        public saveScheduling() {
        }
        
        public saveScheduling(Paricom.KGMWebService.saveSchedulingBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveSchedulingBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonVlue;
        
        public saveSchedulingBody() {
        }
        
        public saveSchedulingBody(string jsonVlue) {
            this.jsonVlue = jsonVlue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveSchedulingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveSchedulingResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.saveSchedulingResponseBody Body;
        
        public saveSchedulingResponse() {
        }
        
        public saveSchedulingResponse(Paricom.KGMWebService.saveSchedulingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveSchedulingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveSchedulingResponseBody() {
        }
        
        public saveSchedulingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.loginBody Body;
        
        public login() {
        }
        
        public login(Paricom.KGMWebService.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginBody() {
        }
        
        public loginBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Paricom.KGMWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsName", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.getVerifyCodeByContactsNameBody Body;
        
        public getVerifyCodeByContactsName() {
        }
        
        public getVerifyCodeByContactsName(Paricom.KGMWebService.getVerifyCodeByContactsNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getVerifyCodeByContactsNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getVerifyCodeByContactsNameBody() {
        }
        
        public getVerifyCodeByContactsNameBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsNameResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.getVerifyCodeByContactsNameResponseBody Body;
        
        public getVerifyCodeByContactsNameResponse() {
        }
        
        public getVerifyCodeByContactsNameResponse(Paricom.KGMWebService.getVerifyCodeByContactsNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getVerifyCodeByContactsNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getVerifyCodeByContactsNameResponseBody() {
        }
        
        public getVerifyCodeByContactsNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.saveCardNoBody Body;
        
        public saveCardNo() {
        }
        
        public saveCardNo(Paricom.KGMWebService.saveCardNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveCardNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public saveCardNoBody() {
        }
        
        public saveCardNoBody(string verifyCode, string cardNo) {
            this.verifyCode = verifyCode;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.saveCardNoResponseBody Body;
        
        public saveCardNoResponse() {
        }
        
        public saveCardNoResponse(Paricom.KGMWebService.saveCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveCardNoResponseBody() {
        }
        
        public saveCardNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.isExistOrderBody Body;
        
        public isExistOrder() {
        }
        
        public isExistOrder(Paricom.KGMWebService.isExistOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isExistOrderBody() {
        }
        
        public isExistOrderBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.isExistOrderResponseBody Body;
        
        public isExistOrderResponse() {
        }
        
        public isExistOrderResponse(Paricom.KGMWebService.isExistOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrderResponseBody() {
        }
        
        public isExistOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.getCardNoByOrderBody Body;
        
        public getCardNoByOrder() {
        }
        
        public getCardNoByOrder(Paricom.KGMWebService.getCardNoByOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getCardNoByOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public getCardNoByOrderBody() {
        }
        
        public getCardNoByOrderBody(string loginName, string cardNo) {
            this.loginName = loginName;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public Paricom.KGMWebService.getCardNoByOrderResponseBody Body;
        
        public getCardNoByOrderResponse() {
        }
        
        public getCardNoByOrderResponse(Paricom.KGMWebService.getCardNoByOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNoByOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCardNoByOrderResponseBody() {
        }
        
        public getCardNoByOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GmWebServletChannel : Paricom.KGMWebService.GmWebServlet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GmWebServletClient : System.ServiceModel.ClientBase<Paricom.KGMWebService.GmWebServlet>, Paricom.KGMWebService.GmWebServlet {
        
        public GmWebServletClient() {
        }
        
        public GmWebServletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.saveSchedulingResponse Paricom.KGMWebService.GmWebServlet.saveScheduling(Paricom.KGMWebService.saveScheduling request) {
            return base.Channel.saveScheduling(request);
        }
        
        public string saveScheduling(string jsonVlue) {
            Paricom.KGMWebService.saveScheduling inValue = new Paricom.KGMWebService.saveScheduling();
            inValue.Body = new Paricom.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            Paricom.KGMWebService.saveSchedulingResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).saveScheduling(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.loginResponse Paricom.KGMWebService.GmWebServlet.login(Paricom.KGMWebService.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string name, string password) {
            Paricom.KGMWebService.login inValue = new Paricom.KGMWebService.login();
            inValue.Body = new Paricom.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            Paricom.KGMWebService.loginResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.getVerifyCodeByContactsNameResponse Paricom.KGMWebService.GmWebServlet.getVerifyCodeByContactsName(Paricom.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsName(request);
        }
        
        public string getVerifyCodeByContactsName(string verifyCode) {
            Paricom.KGMWebService.getVerifyCodeByContactsName inValue = new Paricom.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new Paricom.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            Paricom.KGMWebService.getVerifyCodeByContactsNameResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.saveCardNoResponse Paricom.KGMWebService.GmWebServlet.saveCardNo(Paricom.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNo(request);
        }
        
        public string saveCardNo(string verifyCode, string cardNo) {
            Paricom.KGMWebService.saveCardNo inValue = new Paricom.KGMWebService.saveCardNo();
            inValue.Body = new Paricom.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            Paricom.KGMWebService.saveCardNoResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).saveCardNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.isExistOrderResponse Paricom.KGMWebService.GmWebServlet.isExistOrder(Paricom.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrder(request);
        }
        
        public string isExistOrder(string verifyCode, string loginName) {
            Paricom.KGMWebService.isExistOrder inValue = new Paricom.KGMWebService.isExistOrder();
            inValue.Body = new Paricom.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            Paricom.KGMWebService.isExistOrderResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).isExistOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Paricom.KGMWebService.getCardNoByOrderResponse Paricom.KGMWebService.GmWebServlet.getCardNoByOrder(Paricom.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrder(request);
        }
        
        public string getCardNoByOrder(string loginName, string cardNo) {
            Paricom.KGMWebService.getCardNoByOrder inValue = new Paricom.KGMWebService.getCardNoByOrder();
            inValue.Body = new Paricom.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            Paricom.KGMWebService.getCardNoByOrderResponse retVal = ((Paricom.KGMWebService.GmWebServlet)(this)).getCardNoByOrder(inValue);
            return retVal.Body.@return;
        }
    }
}
