//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKJC.KGMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.jeesite.thinkgem.com/", ConfigurationName="KGMWebService.GmWebServlet")]
    public interface GmWebServlet {
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 jsonVlue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.saveSchedulingResponse saveScheduling(JKJC.KGMWebService.saveScheduling request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.loginResponse login(JKJC.KGMWebService.login request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.getVerifyCodeByContactsNameResponse getVerifyCodeByContactsName(JKJC.KGMWebService.getVerifyCodeByContactsName request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.saveCardNoResponse saveCardNo(JKJC.KGMWebService.saveCardNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.isExistOrderResponse isExistOrder(JKJC.KGMWebService.isExistOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 cardid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.getServiceTimeResponse getServiceTime(JKJC.KGMWebService.getServiceTime request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.getResultResponse getResult(JKJC.KGMWebService.getResult request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.getCardNoByOrderResponse getCardNoByOrder(JKJC.KGMWebService.getCardNoByOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKJC.KGMWebService.fileOutXlsResponse fileOutXls(JKJC.KGMWebService.fileOutXls request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveScheduling {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveScheduling", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.saveSchedulingBody Body;
        
        public saveScheduling() {
        }
        
        public saveScheduling(JKJC.KGMWebService.saveSchedulingBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveSchedulingBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonVlue;
        
        public saveSchedulingBody() {
        }
        
        public saveSchedulingBody(string jsonVlue) {
            this.jsonVlue = jsonVlue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveSchedulingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveSchedulingResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.saveSchedulingResponseBody Body;
        
        public saveSchedulingResponse() {
        }
        
        public saveSchedulingResponse(JKJC.KGMWebService.saveSchedulingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveSchedulingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveSchedulingResponseBody() {
        }
        
        public saveSchedulingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.loginBody Body;
        
        public login() {
        }
        
        public login(JKJC.KGMWebService.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginBody() {
        }
        
        public loginBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(JKJC.KGMWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsName", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getVerifyCodeByContactsNameBody Body;
        
        public getVerifyCodeByContactsName() {
        }
        
        public getVerifyCodeByContactsName(JKJC.KGMWebService.getVerifyCodeByContactsNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getVerifyCodeByContactsNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getVerifyCodeByContactsNameBody() {
        }
        
        public getVerifyCodeByContactsNameBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsNameResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getVerifyCodeByContactsNameResponseBody Body;
        
        public getVerifyCodeByContactsNameResponse() {
        }
        
        public getVerifyCodeByContactsNameResponse(JKJC.KGMWebService.getVerifyCodeByContactsNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getVerifyCodeByContactsNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getVerifyCodeByContactsNameResponseBody() {
        }
        
        public getVerifyCodeByContactsNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.saveCardNoBody Body;
        
        public saveCardNo() {
        }
        
        public saveCardNo(JKJC.KGMWebService.saveCardNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveCardNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public saveCardNoBody() {
        }
        
        public saveCardNoBody(string verifyCode, string cardNo) {
            this.verifyCode = verifyCode;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.saveCardNoResponseBody Body;
        
        public saveCardNoResponse() {
        }
        
        public saveCardNoResponse(JKJC.KGMWebService.saveCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveCardNoResponseBody() {
        }
        
        public saveCardNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.isExistOrderBody Body;
        
        public isExistOrder() {
        }
        
        public isExistOrder(JKJC.KGMWebService.isExistOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isExistOrderBody() {
        }
        
        public isExistOrderBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.isExistOrderResponseBody Body;
        
        public isExistOrderResponse() {
        }
        
        public isExistOrderResponse(JKJC.KGMWebService.isExistOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrderResponseBody() {
        }
        
        public isExistOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTime", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getServiceTimeBody Body;
        
        public getServiceTime() {
        }
        
        public getServiceTime(JKJC.KGMWebService.getServiceTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getServiceTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardid;
        
        public getServiceTimeBody() {
        }
        
        public getServiceTimeBody(string cardid) {
            this.cardid = cardid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTimeResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getServiceTimeResponseBody Body;
        
        public getServiceTimeResponse() {
        }
        
        public getServiceTimeResponse(JKJC.KGMWebService.getServiceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getServiceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getServiceTimeResponseBody() {
        }
        
        public getServiceTimeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getResultBody Body;
        
        public getResult() {
        }
        
        public getResult(JKJC.KGMWebService.getResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getResultBody() {
        }
        
        public getResultBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(JKJC.KGMWebService.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getCardNoByOrderBody Body;
        
        public getCardNoByOrder() {
        }
        
        public getCardNoByOrder(JKJC.KGMWebService.getCardNoByOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getCardNoByOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public getCardNoByOrderBody() {
        }
        
        public getCardNoByOrderBody(string loginName, string cardNo) {
            this.loginName = loginName;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.getCardNoByOrderResponseBody Body;
        
        public getCardNoByOrderResponse() {
        }
        
        public getCardNoByOrderResponse(JKJC.KGMWebService.getCardNoByOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNoByOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCardNoByOrderResponseBody() {
        }
        
        public getCardNoByOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.fileOutXlsBody Body;
        
        public fileOutXls() {
        }
        
        public fileOutXls(JKJC.KGMWebService.fileOutXlsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class fileOutXlsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xlsNmae;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string testDate;
        
        public fileOutXlsBody() {
        }
        
        public fileOutXlsBody(string base64Code, string xlsNmae, string orderId, string testDate) {
            this.base64Code = base64Code;
            this.xlsNmae = xlsNmae;
            this.orderId = orderId;
            this.testDate = testDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXlsResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKJC.KGMWebService.fileOutXlsResponseBody Body;
        
        public fileOutXlsResponse() {
        }
        
        public fileOutXlsResponse(JKJC.KGMWebService.fileOutXlsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fileOutXlsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fileOutXlsResponseBody() {
        }
        
        public fileOutXlsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GmWebServletChannel : JKJC.KGMWebService.GmWebServlet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GmWebServletClient : System.ServiceModel.ClientBase<JKJC.KGMWebService.GmWebServlet>, JKJC.KGMWebService.GmWebServlet {
        
        public GmWebServletClient() {
        }
        
        public GmWebServletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.saveSchedulingResponse JKJC.KGMWebService.GmWebServlet.saveScheduling(JKJC.KGMWebService.saveScheduling request) {
            return base.Channel.saveScheduling(request);
        }
        
        public string saveScheduling(string jsonVlue) {
            JKJC.KGMWebService.saveScheduling inValue = new JKJC.KGMWebService.saveScheduling();
            inValue.Body = new JKJC.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            JKJC.KGMWebService.saveSchedulingResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).saveScheduling(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.loginResponse JKJC.KGMWebService.GmWebServlet.login(JKJC.KGMWebService.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string name, string password) {
            JKJC.KGMWebService.login inValue = new JKJC.KGMWebService.login();
            inValue.Body = new JKJC.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            JKJC.KGMWebService.loginResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.getVerifyCodeByContactsNameResponse JKJC.KGMWebService.GmWebServlet.getVerifyCodeByContactsName(JKJC.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsName(request);
        }
        
        public string getVerifyCodeByContactsName(string verifyCode) {
            JKJC.KGMWebService.getVerifyCodeByContactsName inValue = new JKJC.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new JKJC.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            JKJC.KGMWebService.getVerifyCodeByContactsNameResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.saveCardNoResponse JKJC.KGMWebService.GmWebServlet.saveCardNo(JKJC.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNo(request);
        }
        
        public string saveCardNo(string verifyCode, string cardNo) {
            JKJC.KGMWebService.saveCardNo inValue = new JKJC.KGMWebService.saveCardNo();
            inValue.Body = new JKJC.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            JKJC.KGMWebService.saveCardNoResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).saveCardNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.isExistOrderResponse JKJC.KGMWebService.GmWebServlet.isExistOrder(JKJC.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrder(request);
        }
        
        public string isExistOrder(string verifyCode, string loginName) {
            JKJC.KGMWebService.isExistOrder inValue = new JKJC.KGMWebService.isExistOrder();
            inValue.Body = new JKJC.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            JKJC.KGMWebService.isExistOrderResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).isExistOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.getServiceTimeResponse JKJC.KGMWebService.GmWebServlet.getServiceTime(JKJC.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTime(request);
        }
        
        public string getServiceTime(string cardid) {
            JKJC.KGMWebService.getServiceTime inValue = new JKJC.KGMWebService.getServiceTime();
            inValue.Body = new JKJC.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            JKJC.KGMWebService.getServiceTimeResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).getServiceTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.getResultResponse JKJC.KGMWebService.GmWebServlet.getResult(JKJC.KGMWebService.getResult request) {
            return base.Channel.getResult(request);
        }
        
        public string getResult(string verifyCode) {
            JKJC.KGMWebService.getResult inValue = new JKJC.KGMWebService.getResult();
            inValue.Body = new JKJC.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            JKJC.KGMWebService.getResultResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).getResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.getCardNoByOrderResponse JKJC.KGMWebService.GmWebServlet.getCardNoByOrder(JKJC.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrder(request);
        }
        
        public string getCardNoByOrder(string loginName, string cardNo) {
            JKJC.KGMWebService.getCardNoByOrder inValue = new JKJC.KGMWebService.getCardNoByOrder();
            inValue.Body = new JKJC.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            JKJC.KGMWebService.getCardNoByOrderResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).getCardNoByOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKJC.KGMWebService.fileOutXlsResponse JKJC.KGMWebService.GmWebServlet.fileOutXls(JKJC.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXls(request);
        }
        
        public string fileOutXls(string base64Code, string xlsNmae, string orderId, string testDate) {
            JKJC.KGMWebService.fileOutXls inValue = new JKJC.KGMWebService.fileOutXls();
            inValue.Body = new JKJC.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            JKJC.KGMWebService.fileOutXlsResponse retVal = ((JKJC.KGMWebService.GmWebServlet)(this)).fileOutXls(inValue);
            return retVal.Body.@return;
        }
    }
}
