//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudOperator.KGMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.jeesite.thinkgem.com/", ConfigurationName="KGMWebService.GmWebServlet")]
    public interface GmWebServlet {
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 jsonVlue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.saveSchedulingResponse saveScheduling(CloudOperator.KGMWebService.saveScheduling request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveSchedulingResponse> saveSchedulingAsync(CloudOperator.KGMWebService.saveScheduling request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.isExistOrder_v2Response isExistOrder_v2(CloudOperator.KGMWebService.isExistOrder_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrder_v2Response> isExistOrder_v2Async(CloudOperator.KGMWebService.isExistOrder_v2 request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse getOrderInfoByPeopleNo(CloudOperator.KGMWebService.getOrderInfoByPeopleNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse> getOrderInfoByPeopleNoAsync(CloudOperator.KGMWebService.getOrderInfoByPeopleNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.jsonOutTxtResponse jsonOutTxt(CloudOperator.KGMWebService.jsonOutTxt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.jsonOutTxtResponse> jsonOutTxtAsync(CloudOperator.KGMWebService.jsonOutTxt request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.isTiaoliServiceResponse isTiaoliService(CloudOperator.KGMWebService.isTiaoliService request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isTiaoliServiceResponse> isTiaoliServiceAsync(CloudOperator.KGMWebService.isTiaoliService request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.loginResponse login(CloudOperator.KGMWebService.login request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.loginResponse> loginAsync(CloudOperator.KGMWebService.login request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.fileOutXls_v2Response fileOutXls_v2(CloudOperator.KGMWebService.fileOutXls_v2 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXls_v2Response> fileOutXls_v2Async(CloudOperator.KGMWebService.fileOutXls_v2 request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse getVerifyCodeByContactsName(CloudOperator.KGMWebService.getVerifyCodeByContactsName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse> getVerifyCodeByContactsNameAsync(CloudOperator.KGMWebService.getVerifyCodeByContactsName request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.datacodeOutJsonResponse datacodeOutJson(CloudOperator.KGMWebService.datacodeOutJson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.datacodeOutJsonResponse> datacodeOutJsonAsync(CloudOperator.KGMWebService.datacodeOutJson request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 cardid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.getServiceTimeResponse getServiceTime(CloudOperator.KGMWebService.getServiceTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getServiceTimeResponse> getServiceTimeAsync(CloudOperator.KGMWebService.getServiceTime request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.getCardNoByOrderResponse getCardNoByOrder(CloudOperator.KGMWebService.getCardNoByOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getCardNoByOrderResponse> getCardNoByOrderAsync(CloudOperator.KGMWebService.getCardNoByOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.fileOutXlsResponse fileOutXls(CloudOperator.KGMWebService.fileOutXls request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXlsResponse> fileOutXlsAsync(CloudOperator.KGMWebService.fileOutXls request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.saveCardNoResponse saveCardNo(CloudOperator.KGMWebService.saveCardNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveCardNoResponse> saveCardNoAsync(CloudOperator.KGMWebService.saveCardNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.setUsedResponse setUsed(CloudOperator.KGMWebService.setUsed request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.setUsedResponse> setUsedAsync(CloudOperator.KGMWebService.setUsed request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.isExistOrderResponse isExistOrder(CloudOperator.KGMWebService.isExistOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrderResponse> isExistOrderAsync(CloudOperator.KGMWebService.isExistOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CloudOperator.KGMWebService.getResultResponse getResult(CloudOperator.KGMWebService.getResult request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getResultResponse> getResultAsync(CloudOperator.KGMWebService.getResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveScheduling {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveScheduling", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.saveSchedulingBody Body;
        
        public saveScheduling() {
        }
        
        public saveScheduling(CloudOperator.KGMWebService.saveSchedulingBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveSchedulingBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonVlue;
        
        public saveSchedulingBody() {
        }
        
        public saveSchedulingBody(string jsonVlue) {
            this.jsonVlue = jsonVlue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveSchedulingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveSchedulingResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.saveSchedulingResponseBody Body;
        
        public saveSchedulingResponse() {
        }
        
        public saveSchedulingResponse(CloudOperator.KGMWebService.saveSchedulingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveSchedulingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveSchedulingResponseBody() {
        }
        
        public saveSchedulingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder_v2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder_v2", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isExistOrder_v2Body Body;
        
        public isExistOrder_v2() {
        }
        
        public isExistOrder_v2(CloudOperator.KGMWebService.isExistOrder_v2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrder_v2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string equipmentCode;
        
        public isExistOrder_v2Body() {
        }
        
        public isExistOrder_v2Body(string verifyCode, string loginName, string equipmentCode) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
            this.equipmentCode = equipmentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder_v2Response", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isExistOrder_v2ResponseBody Body;
        
        public isExistOrder_v2Response() {
        }
        
        public isExistOrder_v2Response(CloudOperator.KGMWebService.isExistOrder_v2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrder_v2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrder_v2ResponseBody() {
        }
        
        public isExistOrder_v2ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getOrderInfoByPeopleNoBody Body;
        
        public getOrderInfoByPeopleNo() {
        }
        
        public getOrderInfoByPeopleNo(CloudOperator.KGMWebService.getOrderInfoByPeopleNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getOrderInfoByPeopleNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string peopleNo;
        
        public getOrderInfoByPeopleNoBody() {
        }
        
        public getOrderInfoByPeopleNoBody(string loginName, string peopleNo) {
            this.loginName = loginName;
            this.peopleNo = peopleNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponseBody Body;
        
        public getOrderInfoByPeopleNoResponse() {
        }
        
        public getOrderInfoByPeopleNoResponse(CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getOrderInfoByPeopleNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getOrderInfoByPeopleNoResponseBody() {
        }
        
        public getOrderInfoByPeopleNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxt", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.jsonOutTxtBody Body;
        
        public jsonOutTxt() {
        }
        
        public jsonOutTxt(CloudOperator.KGMWebService.jsonOutTxtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class jsonOutTxtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public jsonOutTxtBody() {
        }
        
        public jsonOutTxtBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxtResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.jsonOutTxtResponseBody Body;
        
        public jsonOutTxtResponse() {
        }
        
        public jsonOutTxtResponse(CloudOperator.KGMWebService.jsonOutTxtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class jsonOutTxtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public jsonOutTxtResponseBody() {
        }
        
        public jsonOutTxtResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isTiaoliService {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isTiaoliService", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isTiaoliServiceBody Body;
        
        public isTiaoliService() {
        }
        
        public isTiaoliService(CloudOperator.KGMWebService.isTiaoliServiceBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isTiaoliServiceBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isTiaoliServiceBody() {
        }
        
        public isTiaoliServiceBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isTiaoliServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isTiaoliServiceResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isTiaoliServiceResponseBody Body;
        
        public isTiaoliServiceResponse() {
        }
        
        public isTiaoliServiceResponse(CloudOperator.KGMWebService.isTiaoliServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isTiaoliServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isTiaoliServiceResponseBody() {
        }
        
        public isTiaoliServiceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.loginBody Body;
        
        public login() {
        }
        
        public login(CloudOperator.KGMWebService.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginBody() {
        }
        
        public loginBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(CloudOperator.KGMWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls_v2 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls_v2", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.fileOutXls_v2Body Body;
        
        public fileOutXls_v2() {
        }
        
        public fileOutXls_v2(CloudOperator.KGMWebService.fileOutXls_v2Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class fileOutXls_v2Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xlsNmae;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string testDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string equipmentCode;
        
        public fileOutXls_v2Body() {
        }
        
        public fileOutXls_v2Body(string base64Code, string xlsNmae, string orderId, string testDate, string equipmentCode) {
            this.base64Code = base64Code;
            this.xlsNmae = xlsNmae;
            this.orderId = orderId;
            this.testDate = testDate;
            this.equipmentCode = equipmentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls_v2Response", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.fileOutXls_v2ResponseBody Body;
        
        public fileOutXls_v2Response() {
        }
        
        public fileOutXls_v2Response(CloudOperator.KGMWebService.fileOutXls_v2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fileOutXls_v2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fileOutXls_v2ResponseBody() {
        }
        
        public fileOutXls_v2ResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsName", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getVerifyCodeByContactsNameBody Body;
        
        public getVerifyCodeByContactsName() {
        }
        
        public getVerifyCodeByContactsName(CloudOperator.KGMWebService.getVerifyCodeByContactsNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getVerifyCodeByContactsNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getVerifyCodeByContactsNameBody() {
        }
        
        public getVerifyCodeByContactsNameBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsNameResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponseBody Body;
        
        public getVerifyCodeByContactsNameResponse() {
        }
        
        public getVerifyCodeByContactsNameResponse(CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getVerifyCodeByContactsNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getVerifyCodeByContactsNameResponseBody() {
        }
        
        public getVerifyCodeByContactsNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJson", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.datacodeOutJsonBody Body;
        
        public datacodeOutJson() {
        }
        
        public datacodeOutJson(CloudOperator.KGMWebService.datacodeOutJsonBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class datacodeOutJsonBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public datacodeOutJsonBody() {
        }
        
        public datacodeOutJsonBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJsonResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.datacodeOutJsonResponseBody Body;
        
        public datacodeOutJsonResponse() {
        }
        
        public datacodeOutJsonResponse(CloudOperator.KGMWebService.datacodeOutJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class datacodeOutJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public datacodeOutJsonResponseBody() {
        }
        
        public datacodeOutJsonResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTime", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getServiceTimeBody Body;
        
        public getServiceTime() {
        }
        
        public getServiceTime(CloudOperator.KGMWebService.getServiceTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getServiceTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardid;
        
        public getServiceTimeBody() {
        }
        
        public getServiceTimeBody(string cardid) {
            this.cardid = cardid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTimeResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getServiceTimeResponseBody Body;
        
        public getServiceTimeResponse() {
        }
        
        public getServiceTimeResponse(CloudOperator.KGMWebService.getServiceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getServiceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getServiceTimeResponseBody() {
        }
        
        public getServiceTimeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getCardNoByOrderBody Body;
        
        public getCardNoByOrder() {
        }
        
        public getCardNoByOrder(CloudOperator.KGMWebService.getCardNoByOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getCardNoByOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public getCardNoByOrderBody() {
        }
        
        public getCardNoByOrderBody(string loginName, string cardNo) {
            this.loginName = loginName;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getCardNoByOrderResponseBody Body;
        
        public getCardNoByOrderResponse() {
        }
        
        public getCardNoByOrderResponse(CloudOperator.KGMWebService.getCardNoByOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNoByOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCardNoByOrderResponseBody() {
        }
        
        public getCardNoByOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.fileOutXlsBody Body;
        
        public fileOutXls() {
        }
        
        public fileOutXls(CloudOperator.KGMWebService.fileOutXlsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class fileOutXlsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xlsNmae;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string testDate;
        
        public fileOutXlsBody() {
        }
        
        public fileOutXlsBody(string base64Code, string xlsNmae, string orderId, string testDate) {
            this.base64Code = base64Code;
            this.xlsNmae = xlsNmae;
            this.orderId = orderId;
            this.testDate = testDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXlsResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.fileOutXlsResponseBody Body;
        
        public fileOutXlsResponse() {
        }
        
        public fileOutXlsResponse(CloudOperator.KGMWebService.fileOutXlsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fileOutXlsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fileOutXlsResponseBody() {
        }
        
        public fileOutXlsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.saveCardNoBody Body;
        
        public saveCardNo() {
        }
        
        public saveCardNo(CloudOperator.KGMWebService.saveCardNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveCardNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public saveCardNoBody() {
        }
        
        public saveCardNoBody(string verifyCode, string cardNo) {
            this.verifyCode = verifyCode;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.saveCardNoResponseBody Body;
        
        public saveCardNoResponse() {
        }
        
        public saveCardNoResponse(CloudOperator.KGMWebService.saveCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveCardNoResponseBody() {
        }
        
        public saveCardNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setUsed {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setUsed", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.setUsedBody Body;
        
        public setUsed() {
        }
        
        public setUsed(CloudOperator.KGMWebService.setUsedBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class setUsedBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public setUsedBody() {
        }
        
        public setUsedBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setUsedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setUsedResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.setUsedResponseBody Body;
        
        public setUsedResponse() {
        }
        
        public setUsedResponse(CloudOperator.KGMWebService.setUsedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setUsedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public setUsedResponseBody() {
        }
        
        public setUsedResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isExistOrderBody Body;
        
        public isExistOrder() {
        }
        
        public isExistOrder(CloudOperator.KGMWebService.isExistOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isExistOrderBody() {
        }
        
        public isExistOrderBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.isExistOrderResponseBody Body;
        
        public isExistOrderResponse() {
        }
        
        public isExistOrderResponse(CloudOperator.KGMWebService.isExistOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrderResponseBody() {
        }
        
        public isExistOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getResultBody Body;
        
        public getResult() {
        }
        
        public getResult(CloudOperator.KGMWebService.getResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getResultBody() {
        }
        
        public getResultBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public CloudOperator.KGMWebService.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(CloudOperator.KGMWebService.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GmWebServletChannel : CloudOperator.KGMWebService.GmWebServlet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GmWebServletClient : System.ServiceModel.ClientBase<CloudOperator.KGMWebService.GmWebServlet>, CloudOperator.KGMWebService.GmWebServlet {
        
        public GmWebServletClient() {
        }
        
        public GmWebServletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.saveSchedulingResponse CloudOperator.KGMWebService.GmWebServlet.saveScheduling(CloudOperator.KGMWebService.saveScheduling request) {
            return base.Channel.saveScheduling(request);
        }
        
        public string saveScheduling(string jsonVlue) {
            CloudOperator.KGMWebService.saveScheduling inValue = new CloudOperator.KGMWebService.saveScheduling();
            inValue.Body = new CloudOperator.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            CloudOperator.KGMWebService.saveSchedulingResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).saveScheduling(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveSchedulingResponse> CloudOperator.KGMWebService.GmWebServlet.saveSchedulingAsync(CloudOperator.KGMWebService.saveScheduling request) {
            return base.Channel.saveSchedulingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveSchedulingResponse> saveSchedulingAsync(string jsonVlue) {
            CloudOperator.KGMWebService.saveScheduling inValue = new CloudOperator.KGMWebService.saveScheduling();
            inValue.Body = new CloudOperator.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).saveSchedulingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.isExistOrder_v2Response CloudOperator.KGMWebService.GmWebServlet.isExistOrder_v2(CloudOperator.KGMWebService.isExistOrder_v2 request) {
            return base.Channel.isExistOrder_v2(request);
        }
        
        public string isExistOrder_v2(string verifyCode, string loginName, string equipmentCode) {
            CloudOperator.KGMWebService.isExistOrder_v2 inValue = new CloudOperator.KGMWebService.isExistOrder_v2();
            inValue.Body = new CloudOperator.KGMWebService.isExistOrder_v2Body();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            inValue.Body.equipmentCode = equipmentCode;
            CloudOperator.KGMWebService.isExistOrder_v2Response retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).isExistOrder_v2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrder_v2Response> CloudOperator.KGMWebService.GmWebServlet.isExistOrder_v2Async(CloudOperator.KGMWebService.isExistOrder_v2 request) {
            return base.Channel.isExistOrder_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrder_v2Response> isExistOrder_v2Async(string verifyCode, string loginName, string equipmentCode) {
            CloudOperator.KGMWebService.isExistOrder_v2 inValue = new CloudOperator.KGMWebService.isExistOrder_v2();
            inValue.Body = new CloudOperator.KGMWebService.isExistOrder_v2Body();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            inValue.Body.equipmentCode = equipmentCode;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).isExistOrder_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse CloudOperator.KGMWebService.GmWebServlet.getOrderInfoByPeopleNo(CloudOperator.KGMWebService.getOrderInfoByPeopleNo request) {
            return base.Channel.getOrderInfoByPeopleNo(request);
        }
        
        public string getOrderInfoByPeopleNo(string loginName, string peopleNo) {
            CloudOperator.KGMWebService.getOrderInfoByPeopleNo inValue = new CloudOperator.KGMWebService.getOrderInfoByPeopleNo();
            inValue.Body = new CloudOperator.KGMWebService.getOrderInfoByPeopleNoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.peopleNo = peopleNo;
            CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).getOrderInfoByPeopleNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse> CloudOperator.KGMWebService.GmWebServlet.getOrderInfoByPeopleNoAsync(CloudOperator.KGMWebService.getOrderInfoByPeopleNo request) {
            return base.Channel.getOrderInfoByPeopleNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.getOrderInfoByPeopleNoResponse> getOrderInfoByPeopleNoAsync(string loginName, string peopleNo) {
            CloudOperator.KGMWebService.getOrderInfoByPeopleNo inValue = new CloudOperator.KGMWebService.getOrderInfoByPeopleNo();
            inValue.Body = new CloudOperator.KGMWebService.getOrderInfoByPeopleNoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.peopleNo = peopleNo;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).getOrderInfoByPeopleNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.jsonOutTxtResponse CloudOperator.KGMWebService.GmWebServlet.jsonOutTxt(CloudOperator.KGMWebService.jsonOutTxt request) {
            return base.Channel.jsonOutTxt(request);
        }
        
        public string jsonOutTxt(string base64Code, string TxtNmae) {
            CloudOperator.KGMWebService.jsonOutTxt inValue = new CloudOperator.KGMWebService.jsonOutTxt();
            inValue.Body = new CloudOperator.KGMWebService.jsonOutTxtBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            CloudOperator.KGMWebService.jsonOutTxtResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).jsonOutTxt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.jsonOutTxtResponse> CloudOperator.KGMWebService.GmWebServlet.jsonOutTxtAsync(CloudOperator.KGMWebService.jsonOutTxt request) {
            return base.Channel.jsonOutTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.jsonOutTxtResponse> jsonOutTxtAsync(string base64Code, string TxtNmae) {
            CloudOperator.KGMWebService.jsonOutTxt inValue = new CloudOperator.KGMWebService.jsonOutTxt();
            inValue.Body = new CloudOperator.KGMWebService.jsonOutTxtBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).jsonOutTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.isTiaoliServiceResponse CloudOperator.KGMWebService.GmWebServlet.isTiaoliService(CloudOperator.KGMWebService.isTiaoliService request) {
            return base.Channel.isTiaoliService(request);
        }
        
        public string isTiaoliService(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.isTiaoliService inValue = new CloudOperator.KGMWebService.isTiaoliService();
            inValue.Body = new CloudOperator.KGMWebService.isTiaoliServiceBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            CloudOperator.KGMWebService.isTiaoliServiceResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).isTiaoliService(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isTiaoliServiceResponse> CloudOperator.KGMWebService.GmWebServlet.isTiaoliServiceAsync(CloudOperator.KGMWebService.isTiaoliService request) {
            return base.Channel.isTiaoliServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.isTiaoliServiceResponse> isTiaoliServiceAsync(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.isTiaoliService inValue = new CloudOperator.KGMWebService.isTiaoliService();
            inValue.Body = new CloudOperator.KGMWebService.isTiaoliServiceBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).isTiaoliServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.loginResponse CloudOperator.KGMWebService.GmWebServlet.login(CloudOperator.KGMWebService.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string name, string password) {
            CloudOperator.KGMWebService.login inValue = new CloudOperator.KGMWebService.login();
            inValue.Body = new CloudOperator.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            CloudOperator.KGMWebService.loginResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.loginResponse> CloudOperator.KGMWebService.GmWebServlet.loginAsync(CloudOperator.KGMWebService.login request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.loginResponse> loginAsync(string name, string password) {
            CloudOperator.KGMWebService.login inValue = new CloudOperator.KGMWebService.login();
            inValue.Body = new CloudOperator.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.fileOutXls_v2Response CloudOperator.KGMWebService.GmWebServlet.fileOutXls_v2(CloudOperator.KGMWebService.fileOutXls_v2 request) {
            return base.Channel.fileOutXls_v2(request);
        }
        
        public string fileOutXls_v2(string base64Code, string xlsNmae, string orderId, string testDate, string equipmentCode) {
            CloudOperator.KGMWebService.fileOutXls_v2 inValue = new CloudOperator.KGMWebService.fileOutXls_v2();
            inValue.Body = new CloudOperator.KGMWebService.fileOutXls_v2Body();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            inValue.Body.equipmentCode = equipmentCode;
            CloudOperator.KGMWebService.fileOutXls_v2Response retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).fileOutXls_v2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXls_v2Response> CloudOperator.KGMWebService.GmWebServlet.fileOutXls_v2Async(CloudOperator.KGMWebService.fileOutXls_v2 request) {
            return base.Channel.fileOutXls_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXls_v2Response> fileOutXls_v2Async(string base64Code, string xlsNmae, string orderId, string testDate, string equipmentCode) {
            CloudOperator.KGMWebService.fileOutXls_v2 inValue = new CloudOperator.KGMWebService.fileOutXls_v2();
            inValue.Body = new CloudOperator.KGMWebService.fileOutXls_v2Body();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            inValue.Body.equipmentCode = equipmentCode;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).fileOutXls_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse CloudOperator.KGMWebService.GmWebServlet.getVerifyCodeByContactsName(CloudOperator.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsName(request);
        }
        
        public string getVerifyCodeByContactsName(string verifyCode) {
            CloudOperator.KGMWebService.getVerifyCodeByContactsName inValue = new CloudOperator.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new CloudOperator.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse> CloudOperator.KGMWebService.GmWebServlet.getVerifyCodeByContactsNameAsync(CloudOperator.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.getVerifyCodeByContactsNameResponse> getVerifyCodeByContactsNameAsync(string verifyCode) {
            CloudOperator.KGMWebService.getVerifyCodeByContactsName inValue = new CloudOperator.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new CloudOperator.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.datacodeOutJsonResponse CloudOperator.KGMWebService.GmWebServlet.datacodeOutJson(CloudOperator.KGMWebService.datacodeOutJson request) {
            return base.Channel.datacodeOutJson(request);
        }
        
        public string datacodeOutJson(string base64Code, string TxtNmae) {
            CloudOperator.KGMWebService.datacodeOutJson inValue = new CloudOperator.KGMWebService.datacodeOutJson();
            inValue.Body = new CloudOperator.KGMWebService.datacodeOutJsonBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            CloudOperator.KGMWebService.datacodeOutJsonResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).datacodeOutJson(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.datacodeOutJsonResponse> CloudOperator.KGMWebService.GmWebServlet.datacodeOutJsonAsync(CloudOperator.KGMWebService.datacodeOutJson request) {
            return base.Channel.datacodeOutJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.datacodeOutJsonResponse> datacodeOutJsonAsync(string base64Code, string TxtNmae) {
            CloudOperator.KGMWebService.datacodeOutJson inValue = new CloudOperator.KGMWebService.datacodeOutJson();
            inValue.Body = new CloudOperator.KGMWebService.datacodeOutJsonBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).datacodeOutJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.getServiceTimeResponse CloudOperator.KGMWebService.GmWebServlet.getServiceTime(CloudOperator.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTime(request);
        }
        
        public string getServiceTime(string cardid) {
            CloudOperator.KGMWebService.getServiceTime inValue = new CloudOperator.KGMWebService.getServiceTime();
            inValue.Body = new CloudOperator.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            CloudOperator.KGMWebService.getServiceTimeResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).getServiceTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getServiceTimeResponse> CloudOperator.KGMWebService.GmWebServlet.getServiceTimeAsync(CloudOperator.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.getServiceTimeResponse> getServiceTimeAsync(string cardid) {
            CloudOperator.KGMWebService.getServiceTime inValue = new CloudOperator.KGMWebService.getServiceTime();
            inValue.Body = new CloudOperator.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).getServiceTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.getCardNoByOrderResponse CloudOperator.KGMWebService.GmWebServlet.getCardNoByOrder(CloudOperator.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrder(request);
        }
        
        public string getCardNoByOrder(string loginName, string cardNo) {
            CloudOperator.KGMWebService.getCardNoByOrder inValue = new CloudOperator.KGMWebService.getCardNoByOrder();
            inValue.Body = new CloudOperator.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            CloudOperator.KGMWebService.getCardNoByOrderResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).getCardNoByOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getCardNoByOrderResponse> CloudOperator.KGMWebService.GmWebServlet.getCardNoByOrderAsync(CloudOperator.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.getCardNoByOrderResponse> getCardNoByOrderAsync(string loginName, string cardNo) {
            CloudOperator.KGMWebService.getCardNoByOrder inValue = new CloudOperator.KGMWebService.getCardNoByOrder();
            inValue.Body = new CloudOperator.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).getCardNoByOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.fileOutXlsResponse CloudOperator.KGMWebService.GmWebServlet.fileOutXls(CloudOperator.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXls(request);
        }
        
        public string fileOutXls(string base64Code, string xlsNmae, string orderId, string testDate) {
            CloudOperator.KGMWebService.fileOutXls inValue = new CloudOperator.KGMWebService.fileOutXls();
            inValue.Body = new CloudOperator.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            CloudOperator.KGMWebService.fileOutXlsResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).fileOutXls(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXlsResponse> CloudOperator.KGMWebService.GmWebServlet.fileOutXlsAsync(CloudOperator.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.fileOutXlsResponse> fileOutXlsAsync(string base64Code, string xlsNmae, string orderId, string testDate) {
            CloudOperator.KGMWebService.fileOutXls inValue = new CloudOperator.KGMWebService.fileOutXls();
            inValue.Body = new CloudOperator.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).fileOutXlsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.saveCardNoResponse CloudOperator.KGMWebService.GmWebServlet.saveCardNo(CloudOperator.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNo(request);
        }
        
        public string saveCardNo(string verifyCode, string cardNo) {
            CloudOperator.KGMWebService.saveCardNo inValue = new CloudOperator.KGMWebService.saveCardNo();
            inValue.Body = new CloudOperator.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            CloudOperator.KGMWebService.saveCardNoResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).saveCardNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveCardNoResponse> CloudOperator.KGMWebService.GmWebServlet.saveCardNoAsync(CloudOperator.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.saveCardNoResponse> saveCardNoAsync(string verifyCode, string cardNo) {
            CloudOperator.KGMWebService.saveCardNo inValue = new CloudOperator.KGMWebService.saveCardNo();
            inValue.Body = new CloudOperator.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).saveCardNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.setUsedResponse CloudOperator.KGMWebService.GmWebServlet.setUsed(CloudOperator.KGMWebService.setUsed request) {
            return base.Channel.setUsed(request);
        }
        
        public string setUsed(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.setUsed inValue = new CloudOperator.KGMWebService.setUsed();
            inValue.Body = new CloudOperator.KGMWebService.setUsedBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            CloudOperator.KGMWebService.setUsedResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).setUsed(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.setUsedResponse> CloudOperator.KGMWebService.GmWebServlet.setUsedAsync(CloudOperator.KGMWebService.setUsed request) {
            return base.Channel.setUsedAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.setUsedResponse> setUsedAsync(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.setUsed inValue = new CloudOperator.KGMWebService.setUsed();
            inValue.Body = new CloudOperator.KGMWebService.setUsedBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).setUsedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.isExistOrderResponse CloudOperator.KGMWebService.GmWebServlet.isExistOrder(CloudOperator.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrder(request);
        }
        
        public string isExistOrder(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.isExistOrder inValue = new CloudOperator.KGMWebService.isExistOrder();
            inValue.Body = new CloudOperator.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            CloudOperator.KGMWebService.isExistOrderResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).isExistOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrderResponse> CloudOperator.KGMWebService.GmWebServlet.isExistOrderAsync(CloudOperator.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.isExistOrderResponse> isExistOrderAsync(string verifyCode, string loginName) {
            CloudOperator.KGMWebService.isExistOrder inValue = new CloudOperator.KGMWebService.isExistOrder();
            inValue.Body = new CloudOperator.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).isExistOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudOperator.KGMWebService.getResultResponse CloudOperator.KGMWebService.GmWebServlet.getResult(CloudOperator.KGMWebService.getResult request) {
            return base.Channel.getResult(request);
        }
        
        public string getResult(string verifyCode) {
            CloudOperator.KGMWebService.getResult inValue = new CloudOperator.KGMWebService.getResult();
            inValue.Body = new CloudOperator.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            CloudOperator.KGMWebService.getResultResponse retVal = ((CloudOperator.KGMWebService.GmWebServlet)(this)).getResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudOperator.KGMWebService.getResultResponse> CloudOperator.KGMWebService.GmWebServlet.getResultAsync(CloudOperator.KGMWebService.getResult request) {
            return base.Channel.getResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudOperator.KGMWebService.getResultResponse> getResultAsync(string verifyCode) {
            CloudOperator.KGMWebService.getResult inValue = new CloudOperator.KGMWebService.getResult();
            inValue.Body = new CloudOperator.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            return ((CloudOperator.KGMWebService.GmWebServlet)(this)).getResultAsync(inValue);
        }
    }
}
