//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JHHY.KGMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.jeesite.thinkgem.com/", ConfigurationName="KGMWebService.GmWebServlet")]
    public interface GmWebServlet {
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 jsonVlue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.saveSchedulingResponse saveScheduling(JHHY.KGMWebService.saveScheduling request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.jsonOutTxtResponse jsonOutTxt(JHHY.KGMWebService.jsonOutTxt request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.getOrderInfoByPeopleNoResponse getOrderInfoByPeopleNo(JHHY.KGMWebService.getOrderInfoByPeopleNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.loginResponse login(JHHY.KGMWebService.login request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.getVerifyCodeByContactsNameResponse getVerifyCodeByContactsName(JHHY.KGMWebService.getVerifyCodeByContactsName request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.datacodeOutJsonResponse datacodeOutJson(JHHY.KGMWebService.datacodeOutJson request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.saveCardNoResponse saveCardNo(JHHY.KGMWebService.saveCardNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.isExistOrderResponse isExistOrder(JHHY.KGMWebService.isExistOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 cardid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.getServiceTimeResponse getServiceTime(JHHY.KGMWebService.getServiceTime request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.getResultResponse getResult(JHHY.KGMWebService.getResult request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.getCardNoByOrderResponse getCardNoByOrder(JHHY.KGMWebService.getCardNoByOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JHHY.KGMWebService.fileOutXlsResponse fileOutXls(JHHY.KGMWebService.fileOutXls request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveScheduling {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveScheduling", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.saveSchedulingBody Body;
        
        public saveScheduling() {
        }
        
        public saveScheduling(JHHY.KGMWebService.saveSchedulingBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveSchedulingBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonVlue;
        
        public saveSchedulingBody() {
        }
        
        public saveSchedulingBody(string jsonVlue) {
            this.jsonVlue = jsonVlue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveSchedulingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveSchedulingResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.saveSchedulingResponseBody Body;
        
        public saveSchedulingResponse() {
        }
        
        public saveSchedulingResponse(JHHY.KGMWebService.saveSchedulingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveSchedulingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveSchedulingResponseBody() {
        }
        
        public saveSchedulingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxt", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.jsonOutTxtBody Body;
        
        public jsonOutTxt() {
        }
        
        public jsonOutTxt(JHHY.KGMWebService.jsonOutTxtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class jsonOutTxtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public jsonOutTxtBody() {
        }
        
        public jsonOutTxtBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxtResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.jsonOutTxtResponseBody Body;
        
        public jsonOutTxtResponse() {
        }
        
        public jsonOutTxtResponse(JHHY.KGMWebService.jsonOutTxtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class jsonOutTxtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public jsonOutTxtResponseBody() {
        }
        
        public jsonOutTxtResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getOrderInfoByPeopleNoBody Body;
        
        public getOrderInfoByPeopleNo() {
        }
        
        public getOrderInfoByPeopleNo(JHHY.KGMWebService.getOrderInfoByPeopleNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getOrderInfoByPeopleNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string peopleNo;
        
        public getOrderInfoByPeopleNoBody() {
        }
        
        public getOrderInfoByPeopleNoBody(string loginName, string peopleNo) {
            this.loginName = loginName;
            this.peopleNo = peopleNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getOrderInfoByPeopleNoResponseBody Body;
        
        public getOrderInfoByPeopleNoResponse() {
        }
        
        public getOrderInfoByPeopleNoResponse(JHHY.KGMWebService.getOrderInfoByPeopleNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getOrderInfoByPeopleNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getOrderInfoByPeopleNoResponseBody() {
        }
        
        public getOrderInfoByPeopleNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.loginBody Body;
        
        public login() {
        }
        
        public login(JHHY.KGMWebService.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginBody() {
        }
        
        public loginBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(JHHY.KGMWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsName", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getVerifyCodeByContactsNameBody Body;
        
        public getVerifyCodeByContactsName() {
        }
        
        public getVerifyCodeByContactsName(JHHY.KGMWebService.getVerifyCodeByContactsNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getVerifyCodeByContactsNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getVerifyCodeByContactsNameBody() {
        }
        
        public getVerifyCodeByContactsNameBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsNameResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getVerifyCodeByContactsNameResponseBody Body;
        
        public getVerifyCodeByContactsNameResponse() {
        }
        
        public getVerifyCodeByContactsNameResponse(JHHY.KGMWebService.getVerifyCodeByContactsNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getVerifyCodeByContactsNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getVerifyCodeByContactsNameResponseBody() {
        }
        
        public getVerifyCodeByContactsNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJson", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.datacodeOutJsonBody Body;
        
        public datacodeOutJson() {
        }
        
        public datacodeOutJson(JHHY.KGMWebService.datacodeOutJsonBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class datacodeOutJsonBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public datacodeOutJsonBody() {
        }
        
        public datacodeOutJsonBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJsonResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.datacodeOutJsonResponseBody Body;
        
        public datacodeOutJsonResponse() {
        }
        
        public datacodeOutJsonResponse(JHHY.KGMWebService.datacodeOutJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class datacodeOutJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public datacodeOutJsonResponseBody() {
        }
        
        public datacodeOutJsonResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.saveCardNoBody Body;
        
        public saveCardNo() {
        }
        
        public saveCardNo(JHHY.KGMWebService.saveCardNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveCardNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public saveCardNoBody() {
        }
        
        public saveCardNoBody(string verifyCode, string cardNo) {
            this.verifyCode = verifyCode;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.saveCardNoResponseBody Body;
        
        public saveCardNoResponse() {
        }
        
        public saveCardNoResponse(JHHY.KGMWebService.saveCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveCardNoResponseBody() {
        }
        
        public saveCardNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.isExistOrderBody Body;
        
        public isExistOrder() {
        }
        
        public isExistOrder(JHHY.KGMWebService.isExistOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isExistOrderBody() {
        }
        
        public isExistOrderBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.isExistOrderResponseBody Body;
        
        public isExistOrderResponse() {
        }
        
        public isExistOrderResponse(JHHY.KGMWebService.isExistOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrderResponseBody() {
        }
        
        public isExistOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTime", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getServiceTimeBody Body;
        
        public getServiceTime() {
        }
        
        public getServiceTime(JHHY.KGMWebService.getServiceTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getServiceTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardid;
        
        public getServiceTimeBody() {
        }
        
        public getServiceTimeBody(string cardid) {
            this.cardid = cardid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTimeResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getServiceTimeResponseBody Body;
        
        public getServiceTimeResponse() {
        }
        
        public getServiceTimeResponse(JHHY.KGMWebService.getServiceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getServiceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getServiceTimeResponseBody() {
        }
        
        public getServiceTimeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getResultBody Body;
        
        public getResult() {
        }
        
        public getResult(JHHY.KGMWebService.getResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getResultBody() {
        }
        
        public getResultBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(JHHY.KGMWebService.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getCardNoByOrderBody Body;
        
        public getCardNoByOrder() {
        }
        
        public getCardNoByOrder(JHHY.KGMWebService.getCardNoByOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getCardNoByOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public getCardNoByOrderBody() {
        }
        
        public getCardNoByOrderBody(string loginName, string cardNo) {
            this.loginName = loginName;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.getCardNoByOrderResponseBody Body;
        
        public getCardNoByOrderResponse() {
        }
        
        public getCardNoByOrderResponse(JHHY.KGMWebService.getCardNoByOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNoByOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCardNoByOrderResponseBody() {
        }
        
        public getCardNoByOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.fileOutXlsBody Body;
        
        public fileOutXls() {
        }
        
        public fileOutXls(JHHY.KGMWebService.fileOutXlsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class fileOutXlsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xlsNmae;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string testDate;
        
        public fileOutXlsBody() {
        }
        
        public fileOutXlsBody(string base64Code, string xlsNmae, string orderId, string testDate) {
            this.base64Code = base64Code;
            this.xlsNmae = xlsNmae;
            this.orderId = orderId;
            this.testDate = testDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXlsResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JHHY.KGMWebService.fileOutXlsResponseBody Body;
        
        public fileOutXlsResponse() {
        }
        
        public fileOutXlsResponse(JHHY.KGMWebService.fileOutXlsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fileOutXlsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fileOutXlsResponseBody() {
        }
        
        public fileOutXlsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GmWebServletChannel : JHHY.KGMWebService.GmWebServlet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GmWebServletClient : System.ServiceModel.ClientBase<JHHY.KGMWebService.GmWebServlet>, JHHY.KGMWebService.GmWebServlet {
        
        public GmWebServletClient() {
        }
        
        public GmWebServletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.saveSchedulingResponse JHHY.KGMWebService.GmWebServlet.saveScheduling(JHHY.KGMWebService.saveScheduling request) {
            return base.Channel.saveScheduling(request);
        }
        
        public string saveScheduling(string jsonVlue) {
            JHHY.KGMWebService.saveScheduling inValue = new JHHY.KGMWebService.saveScheduling();
            inValue.Body = new JHHY.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            JHHY.KGMWebService.saveSchedulingResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).saveScheduling(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.jsonOutTxtResponse JHHY.KGMWebService.GmWebServlet.jsonOutTxt(JHHY.KGMWebService.jsonOutTxt request) {
            return base.Channel.jsonOutTxt(request);
        }
        
        public string jsonOutTxt(string base64Code, string TxtNmae) {
            JHHY.KGMWebService.jsonOutTxt inValue = new JHHY.KGMWebService.jsonOutTxt();
            inValue.Body = new JHHY.KGMWebService.jsonOutTxtBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            JHHY.KGMWebService.jsonOutTxtResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).jsonOutTxt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.getOrderInfoByPeopleNoResponse JHHY.KGMWebService.GmWebServlet.getOrderInfoByPeopleNo(JHHY.KGMWebService.getOrderInfoByPeopleNo request) {
            return base.Channel.getOrderInfoByPeopleNo(request);
        }
        
        public string getOrderInfoByPeopleNo(string loginName, string peopleNo) {
            JHHY.KGMWebService.getOrderInfoByPeopleNo inValue = new JHHY.KGMWebService.getOrderInfoByPeopleNo();
            inValue.Body = new JHHY.KGMWebService.getOrderInfoByPeopleNoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.peopleNo = peopleNo;
            JHHY.KGMWebService.getOrderInfoByPeopleNoResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).getOrderInfoByPeopleNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.loginResponse JHHY.KGMWebService.GmWebServlet.login(JHHY.KGMWebService.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string name, string password) {
            JHHY.KGMWebService.login inValue = new JHHY.KGMWebService.login();
            inValue.Body = new JHHY.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            JHHY.KGMWebService.loginResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.getVerifyCodeByContactsNameResponse JHHY.KGMWebService.GmWebServlet.getVerifyCodeByContactsName(JHHY.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsName(request);
        }
        
        public string getVerifyCodeByContactsName(string verifyCode) {
            JHHY.KGMWebService.getVerifyCodeByContactsName inValue = new JHHY.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new JHHY.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            JHHY.KGMWebService.getVerifyCodeByContactsNameResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.datacodeOutJsonResponse JHHY.KGMWebService.GmWebServlet.datacodeOutJson(JHHY.KGMWebService.datacodeOutJson request) {
            return base.Channel.datacodeOutJson(request);
        }
        
        public string datacodeOutJson(string base64Code, string TxtNmae) {
            JHHY.KGMWebService.datacodeOutJson inValue = new JHHY.KGMWebService.datacodeOutJson();
            inValue.Body = new JHHY.KGMWebService.datacodeOutJsonBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            JHHY.KGMWebService.datacodeOutJsonResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).datacodeOutJson(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.saveCardNoResponse JHHY.KGMWebService.GmWebServlet.saveCardNo(JHHY.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNo(request);
        }
        
        public string saveCardNo(string verifyCode, string cardNo) {
            JHHY.KGMWebService.saveCardNo inValue = new JHHY.KGMWebService.saveCardNo();
            inValue.Body = new JHHY.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            JHHY.KGMWebService.saveCardNoResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).saveCardNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.isExistOrderResponse JHHY.KGMWebService.GmWebServlet.isExistOrder(JHHY.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrder(request);
        }
        
        public string isExistOrder(string verifyCode, string loginName) {
            JHHY.KGMWebService.isExistOrder inValue = new JHHY.KGMWebService.isExistOrder();
            inValue.Body = new JHHY.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            JHHY.KGMWebService.isExistOrderResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).isExistOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.getServiceTimeResponse JHHY.KGMWebService.GmWebServlet.getServiceTime(JHHY.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTime(request);
        }
        
        public string getServiceTime(string cardid) {
            JHHY.KGMWebService.getServiceTime inValue = new JHHY.KGMWebService.getServiceTime();
            inValue.Body = new JHHY.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            JHHY.KGMWebService.getServiceTimeResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).getServiceTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.getResultResponse JHHY.KGMWebService.GmWebServlet.getResult(JHHY.KGMWebService.getResult request) {
            return base.Channel.getResult(request);
        }
        
        public string getResult(string verifyCode) {
            JHHY.KGMWebService.getResult inValue = new JHHY.KGMWebService.getResult();
            inValue.Body = new JHHY.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            JHHY.KGMWebService.getResultResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).getResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.getCardNoByOrderResponse JHHY.KGMWebService.GmWebServlet.getCardNoByOrder(JHHY.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrder(request);
        }
        
        public string getCardNoByOrder(string loginName, string cardNo) {
            JHHY.KGMWebService.getCardNoByOrder inValue = new JHHY.KGMWebService.getCardNoByOrder();
            inValue.Body = new JHHY.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            JHHY.KGMWebService.getCardNoByOrderResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).getCardNoByOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JHHY.KGMWebService.fileOutXlsResponse JHHY.KGMWebService.GmWebServlet.fileOutXls(JHHY.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXls(request);
        }
        
        public string fileOutXls(string base64Code, string xlsNmae, string orderId, string testDate) {
            JHHY.KGMWebService.fileOutXls inValue = new JHHY.KGMWebService.fileOutXls();
            inValue.Body = new JHHY.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            JHHY.KGMWebService.fileOutXlsResponse retVal = ((JHHY.KGMWebService.GmWebServlet)(this)).fileOutXls(inValue);
            return retVal.Body.@return;
        }
    }
}
