//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.DataService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        Admin.DataService.GetDataResponse GetData(Admin.DataService.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<Admin.DataService.GetDataResponse> GetDataAsync(Admin.DataService.GetDataRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 dataJson 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendData", ReplyAction="*")]
        Admin.DataService.SendDataResponse SendData(Admin.DataService.SendDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendData", ReplyAction="*")]
        System.Threading.Tasks.Task<Admin.DataService.SendDataResponse> SendDataAsync(Admin.DataService.SendDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public Admin.DataService.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(Admin.DataService.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Admin.DataService.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(Admin.DataService.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(string GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendData", Namespace="http://tempuri.org/", Order=0)]
        public Admin.DataService.SendDataRequestBody Body;
        
        public SendDataRequest() {
        }
        
        public SendDataRequest(Admin.DataService.SendDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataJson;
        
        public SendDataRequestBody() {
        }
        
        public SendDataRequestBody(string dataJson) {
            this.dataJson = dataJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Admin.DataService.SendDataResponseBody Body;
        
        public SendDataResponse() {
        }
        
        public SendDataResponse(Admin.DataService.SendDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendDataResult;
        
        public SendDataResponseBody() {
        }
        
        public SendDataResponseBody(int SendDataResult) {
            this.SendDataResult = SendDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : Admin.DataService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<Admin.DataService.DataServiceSoap>, Admin.DataService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Admin.DataService.GetDataResponse Admin.DataService.DataServiceSoap.GetData(Admin.DataService.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public string GetData(string verifyCode) {
            Admin.DataService.GetDataRequest inValue = new Admin.DataService.GetDataRequest();
            inValue.Body = new Admin.DataService.GetDataRequestBody();
            inValue.Body.verifyCode = verifyCode;
            Admin.DataService.GetDataResponse retVal = ((Admin.DataService.DataServiceSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Admin.DataService.GetDataResponse> Admin.DataService.DataServiceSoap.GetDataAsync(Admin.DataService.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Admin.DataService.GetDataResponse> GetDataAsync(string verifyCode) {
            Admin.DataService.GetDataRequest inValue = new Admin.DataService.GetDataRequest();
            inValue.Body = new Admin.DataService.GetDataRequestBody();
            inValue.Body.verifyCode = verifyCode;
            return ((Admin.DataService.DataServiceSoap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Admin.DataService.SendDataResponse Admin.DataService.DataServiceSoap.SendData(Admin.DataService.SendDataRequest request) {
            return base.Channel.SendData(request);
        }
        
        public int SendData(string dataJson) {
            Admin.DataService.SendDataRequest inValue = new Admin.DataService.SendDataRequest();
            inValue.Body = new Admin.DataService.SendDataRequestBody();
            inValue.Body.dataJson = dataJson;
            Admin.DataService.SendDataResponse retVal = ((Admin.DataService.DataServiceSoap)(this)).SendData(inValue);
            return retVal.Body.SendDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Admin.DataService.SendDataResponse> Admin.DataService.DataServiceSoap.SendDataAsync(Admin.DataService.SendDataRequest request) {
            return base.Channel.SendDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Admin.DataService.SendDataResponse> SendDataAsync(string dataJson) {
            Admin.DataService.SendDataRequest inValue = new Admin.DataService.SendDataRequest();
            inValue.Body = new Admin.DataService.SendDataRequestBody();
            inValue.Body.dataJson = dataJson;
            return ((Admin.DataService.DataServiceSoap)(this)).SendDataAsync(inValue);
        }
    }
}
