//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JKApp.KGMWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService.jeesite.thinkgem.com/", ConfigurationName="KGMWebService.GmWebServlet")]
    public interface GmWebServlet {
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 jsonVlue 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.saveSchedulingResponse saveScheduling(JKApp.KGMWebService.saveScheduling request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.saveSchedulingResponse> saveSchedulingAsync(JKApp.KGMWebService.saveScheduling request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.jsonOutTxtResponse jsonOutTxt(JKApp.KGMWebService.jsonOutTxt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.jsonOutTxtResponse> jsonOutTxtAsync(JKApp.KGMWebService.jsonOutTxt request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.getOrderInfoByPeopleNoResponse getOrderInfoByPeopleNo(JKApp.KGMWebService.getOrderInfoByPeopleNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getOrderInfoByPeopleNoResponse> getOrderInfoByPeopleNoAsync(JKApp.KGMWebService.getOrderInfoByPeopleNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.loginResponse login(JKApp.KGMWebService.login request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.loginResponse> loginAsync(JKApp.KGMWebService.login request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.getVerifyCodeByContactsNameResponse getVerifyCodeByContactsName(JKApp.KGMWebService.getVerifyCodeByContactsName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getVerifyCodeByContactsNameResponse> getVerifyCodeByContactsNameAsync(JKApp.KGMWebService.getVerifyCodeByContactsName request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.datacodeOutJsonResponse datacodeOutJson(JKApp.KGMWebService.datacodeOutJson request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.datacodeOutJsonResponse> datacodeOutJsonAsync(JKApp.KGMWebService.datacodeOutJson request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.saveCardNoResponse saveCardNo(JKApp.KGMWebService.saveCardNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.saveCardNoResponse> saveCardNoAsync(JKApp.KGMWebService.saveCardNo request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.isExistOrderResponse isExistOrder(JKApp.KGMWebService.isExistOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.isExistOrderResponse> isExistOrderAsync(JKApp.KGMWebService.isExistOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 cardid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.getServiceTimeResponse getServiceTime(JKApp.KGMWebService.getServiceTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getServiceTimeResponse> getServiceTimeAsync(JKApp.KGMWebService.getServiceTime request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 verifyCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.getResultResponse getResult(JKApp.KGMWebService.getResult request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getResultResponse> getResultAsync(JKApp.KGMWebService.getResult request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.getCardNoByOrderResponse getCardNoByOrder(JKApp.KGMWebService.getCardNoByOrder request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getCardNoByOrderResponse> getCardNoByOrderAsync(JKApp.KGMWebService.getCardNoByOrder request);
        
        // CODEGEN: 命名空间 http://impl.webService.jeesite.thinkgem.com/ 的元素名称 base64Code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        JKApp.KGMWebService.fileOutXlsResponse fileOutXls(JKApp.KGMWebService.fileOutXls request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JKApp.KGMWebService.fileOutXlsResponse> fileOutXlsAsync(JKApp.KGMWebService.fileOutXls request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveScheduling {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveScheduling", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.saveSchedulingBody Body;
        
        public saveScheduling() {
        }
        
        public saveScheduling(JKApp.KGMWebService.saveSchedulingBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveSchedulingBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonVlue;
        
        public saveSchedulingBody() {
        }
        
        public saveSchedulingBody(string jsonVlue) {
            this.jsonVlue = jsonVlue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveSchedulingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveSchedulingResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.saveSchedulingResponseBody Body;
        
        public saveSchedulingResponse() {
        }
        
        public saveSchedulingResponse(JKApp.KGMWebService.saveSchedulingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveSchedulingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveSchedulingResponseBody() {
        }
        
        public saveSchedulingResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxt", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.jsonOutTxtBody Body;
        
        public jsonOutTxt() {
        }
        
        public jsonOutTxt(JKApp.KGMWebService.jsonOutTxtBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class jsonOutTxtBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public jsonOutTxtBody() {
        }
        
        public jsonOutTxtBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class jsonOutTxtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="jsonOutTxtResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.jsonOutTxtResponseBody Body;
        
        public jsonOutTxtResponse() {
        }
        
        public jsonOutTxtResponse(JKApp.KGMWebService.jsonOutTxtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class jsonOutTxtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public jsonOutTxtResponseBody() {
        }
        
        public jsonOutTxtResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getOrderInfoByPeopleNoBody Body;
        
        public getOrderInfoByPeopleNo() {
        }
        
        public getOrderInfoByPeopleNo(JKApp.KGMWebService.getOrderInfoByPeopleNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getOrderInfoByPeopleNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string peopleNo;
        
        public getOrderInfoByPeopleNoBody() {
        }
        
        public getOrderInfoByPeopleNoBody(string loginName, string peopleNo) {
            this.loginName = loginName;
            this.peopleNo = peopleNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoByPeopleNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoByPeopleNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getOrderInfoByPeopleNoResponseBody Body;
        
        public getOrderInfoByPeopleNoResponse() {
        }
        
        public getOrderInfoByPeopleNoResponse(JKApp.KGMWebService.getOrderInfoByPeopleNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getOrderInfoByPeopleNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getOrderInfoByPeopleNoResponseBody() {
        }
        
        public getOrderInfoByPeopleNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.loginBody Body;
        
        public login() {
        }
        
        public login(JKApp.KGMWebService.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginBody() {
        }
        
        public loginBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(JKApp.KGMWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsName", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getVerifyCodeByContactsNameBody Body;
        
        public getVerifyCodeByContactsName() {
        }
        
        public getVerifyCodeByContactsName(JKApp.KGMWebService.getVerifyCodeByContactsNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getVerifyCodeByContactsNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getVerifyCodeByContactsNameBody() {
        }
        
        public getVerifyCodeByContactsNameBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerifyCodeByContactsNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVerifyCodeByContactsNameResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getVerifyCodeByContactsNameResponseBody Body;
        
        public getVerifyCodeByContactsNameResponse() {
        }
        
        public getVerifyCodeByContactsNameResponse(JKApp.KGMWebService.getVerifyCodeByContactsNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getVerifyCodeByContactsNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getVerifyCodeByContactsNameResponseBody() {
        }
        
        public getVerifyCodeByContactsNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJson {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJson", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.datacodeOutJsonBody Body;
        
        public datacodeOutJson() {
        }
        
        public datacodeOutJson(JKApp.KGMWebService.datacodeOutJsonBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class datacodeOutJsonBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TxtNmae;
        
        public datacodeOutJsonBody() {
        }
        
        public datacodeOutJsonBody(string base64Code, string TxtNmae) {
            this.base64Code = base64Code;
            this.TxtNmae = TxtNmae;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class datacodeOutJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="datacodeOutJsonResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.datacodeOutJsonResponseBody Body;
        
        public datacodeOutJsonResponse() {
        }
        
        public datacodeOutJsonResponse(JKApp.KGMWebService.datacodeOutJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class datacodeOutJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public datacodeOutJsonResponseBody() {
        }
        
        public datacodeOutJsonResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNo", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.saveCardNoBody Body;
        
        public saveCardNo() {
        }
        
        public saveCardNo(JKApp.KGMWebService.saveCardNoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class saveCardNoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public saveCardNoBody() {
        }
        
        public saveCardNoBody(string verifyCode, string cardNo) {
            this.verifyCode = verifyCode;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveCardNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveCardNoResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.saveCardNoResponseBody Body;
        
        public saveCardNoResponse() {
        }
        
        public saveCardNoResponse(JKApp.KGMWebService.saveCardNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class saveCardNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public saveCardNoResponseBody() {
        }
        
        public saveCardNoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.isExistOrderBody Body;
        
        public isExistOrder() {
        }
        
        public isExistOrder(JKApp.KGMWebService.isExistOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class isExistOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public isExistOrderBody() {
        }
        
        public isExistOrderBody(string verifyCode, string loginName) {
            this.verifyCode = verifyCode;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isExistOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isExistOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.isExistOrderResponseBody Body;
        
        public isExistOrderResponse() {
        }
        
        public isExistOrderResponse(JKApp.KGMWebService.isExistOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class isExistOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public isExistOrderResponseBody() {
        }
        
        public isExistOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTime", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getServiceTimeBody Body;
        
        public getServiceTime() {
        }
        
        public getServiceTime(JKApp.KGMWebService.getServiceTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getServiceTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardid;
        
        public getServiceTimeBody() {
        }
        
        public getServiceTimeBody(string cardid) {
            this.cardid = cardid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServiceTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getServiceTimeResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getServiceTimeResponseBody Body;
        
        public getServiceTimeResponse() {
        }
        
        public getServiceTimeResponse(JKApp.KGMWebService.getServiceTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getServiceTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getServiceTimeResponseBody() {
        }
        
        public getServiceTimeResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResult", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getResultBody Body;
        
        public getResult() {
        }
        
        public getResult(JKApp.KGMWebService.getResultBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getResultBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string verifyCode;
        
        public getResultBody() {
        }
        
        public getResultBody(string verifyCode) {
            this.verifyCode = verifyCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getResultResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getResultResponseBody Body;
        
        public getResultResponse() {
        }
        
        public getResultResponse(JKApp.KGMWebService.getResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getResultResponseBody() {
        }
        
        public getResultResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrder", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getCardNoByOrderBody Body;
        
        public getCardNoByOrder() {
        }
        
        public getCardNoByOrder(JKApp.KGMWebService.getCardNoByOrderBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class getCardNoByOrderBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cardNo;
        
        public getCardNoByOrderBody() {
        }
        
        public getCardNoByOrderBody(string loginName, string cardNo) {
            this.loginName = loginName;
            this.cardNo = cardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNoByOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNoByOrderResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.getCardNoByOrderResponseBody Body;
        
        public getCardNoByOrderResponse() {
        }
        
        public getCardNoByOrderResponse(JKApp.KGMWebService.getCardNoByOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCardNoByOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCardNoByOrderResponseBody() {
        }
        
        public getCardNoByOrderResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXls {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXls", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.fileOutXlsBody Body;
        
        public fileOutXls() {
        }
        
        public fileOutXls(JKApp.KGMWebService.fileOutXlsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://impl.webService.jeesite.thinkgem.com/")]
    public partial class fileOutXlsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string base64Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xlsNmae;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string testDate;
        
        public fileOutXlsBody() {
        }
        
        public fileOutXlsBody(string base64Code, string xlsNmae, string orderId, string testDate) {
            this.base64Code = base64Code;
            this.xlsNmae = xlsNmae;
            this.orderId = orderId;
            this.testDate = testDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileOutXlsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileOutXlsResponse", Namespace="http://webService.jeesite.thinkgem.com/", Order=0)]
        public JKApp.KGMWebService.fileOutXlsResponseBody Body;
        
        public fileOutXlsResponse() {
        }
        
        public fileOutXlsResponse(JKApp.KGMWebService.fileOutXlsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class fileOutXlsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public fileOutXlsResponseBody() {
        }
        
        public fileOutXlsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GmWebServletChannel : JKApp.KGMWebService.GmWebServlet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GmWebServletClient : System.ServiceModel.ClientBase<JKApp.KGMWebService.GmWebServlet>, JKApp.KGMWebService.GmWebServlet {
        
        public GmWebServletClient() {
        }
        
        public GmWebServletClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GmWebServletClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.saveSchedulingResponse JKApp.KGMWebService.GmWebServlet.saveScheduling(JKApp.KGMWebService.saveScheduling request) {
            return base.Channel.saveScheduling(request);
        }
        
        public string saveScheduling(string jsonVlue) {
            JKApp.KGMWebService.saveScheduling inValue = new JKApp.KGMWebService.saveScheduling();
            inValue.Body = new JKApp.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            JKApp.KGMWebService.saveSchedulingResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).saveScheduling(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.saveSchedulingResponse> JKApp.KGMWebService.GmWebServlet.saveSchedulingAsync(JKApp.KGMWebService.saveScheduling request) {
            return base.Channel.saveSchedulingAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.saveSchedulingResponse> saveSchedulingAsync(string jsonVlue) {
            JKApp.KGMWebService.saveScheduling inValue = new JKApp.KGMWebService.saveScheduling();
            inValue.Body = new JKApp.KGMWebService.saveSchedulingBody();
            inValue.Body.jsonVlue = jsonVlue;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).saveSchedulingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.jsonOutTxtResponse JKApp.KGMWebService.GmWebServlet.jsonOutTxt(JKApp.KGMWebService.jsonOutTxt request) {
            return base.Channel.jsonOutTxt(request);
        }
        
        public string jsonOutTxt(string base64Code, string TxtNmae) {
            JKApp.KGMWebService.jsonOutTxt inValue = new JKApp.KGMWebService.jsonOutTxt();
            inValue.Body = new JKApp.KGMWebService.jsonOutTxtBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            JKApp.KGMWebService.jsonOutTxtResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).jsonOutTxt(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.jsonOutTxtResponse> JKApp.KGMWebService.GmWebServlet.jsonOutTxtAsync(JKApp.KGMWebService.jsonOutTxt request) {
            return base.Channel.jsonOutTxtAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.jsonOutTxtResponse> jsonOutTxtAsync(string base64Code, string TxtNmae) {
            JKApp.KGMWebService.jsonOutTxt inValue = new JKApp.KGMWebService.jsonOutTxt();
            inValue.Body = new JKApp.KGMWebService.jsonOutTxtBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).jsonOutTxtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.getOrderInfoByPeopleNoResponse JKApp.KGMWebService.GmWebServlet.getOrderInfoByPeopleNo(JKApp.KGMWebService.getOrderInfoByPeopleNo request) {
            return base.Channel.getOrderInfoByPeopleNo(request);
        }
        
        public string getOrderInfoByPeopleNo(string loginName, string peopleNo) {
            JKApp.KGMWebService.getOrderInfoByPeopleNo inValue = new JKApp.KGMWebService.getOrderInfoByPeopleNo();
            inValue.Body = new JKApp.KGMWebService.getOrderInfoByPeopleNoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.peopleNo = peopleNo;
            JKApp.KGMWebService.getOrderInfoByPeopleNoResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).getOrderInfoByPeopleNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getOrderInfoByPeopleNoResponse> JKApp.KGMWebService.GmWebServlet.getOrderInfoByPeopleNoAsync(JKApp.KGMWebService.getOrderInfoByPeopleNo request) {
            return base.Channel.getOrderInfoByPeopleNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.getOrderInfoByPeopleNoResponse> getOrderInfoByPeopleNoAsync(string loginName, string peopleNo) {
            JKApp.KGMWebService.getOrderInfoByPeopleNo inValue = new JKApp.KGMWebService.getOrderInfoByPeopleNo();
            inValue.Body = new JKApp.KGMWebService.getOrderInfoByPeopleNoBody();
            inValue.Body.loginName = loginName;
            inValue.Body.peopleNo = peopleNo;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).getOrderInfoByPeopleNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.loginResponse JKApp.KGMWebService.GmWebServlet.login(JKApp.KGMWebService.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string name, string password) {
            JKApp.KGMWebService.login inValue = new JKApp.KGMWebService.login();
            inValue.Body = new JKApp.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            JKApp.KGMWebService.loginResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.loginResponse> JKApp.KGMWebService.GmWebServlet.loginAsync(JKApp.KGMWebService.login request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.loginResponse> loginAsync(string name, string password) {
            JKApp.KGMWebService.login inValue = new JKApp.KGMWebService.login();
            inValue.Body = new JKApp.KGMWebService.loginBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.getVerifyCodeByContactsNameResponse JKApp.KGMWebService.GmWebServlet.getVerifyCodeByContactsName(JKApp.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsName(request);
        }
        
        public string getVerifyCodeByContactsName(string verifyCode) {
            JKApp.KGMWebService.getVerifyCodeByContactsName inValue = new JKApp.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new JKApp.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            JKApp.KGMWebService.getVerifyCodeByContactsNameResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getVerifyCodeByContactsNameResponse> JKApp.KGMWebService.GmWebServlet.getVerifyCodeByContactsNameAsync(JKApp.KGMWebService.getVerifyCodeByContactsName request) {
            return base.Channel.getVerifyCodeByContactsNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.getVerifyCodeByContactsNameResponse> getVerifyCodeByContactsNameAsync(string verifyCode) {
            JKApp.KGMWebService.getVerifyCodeByContactsName inValue = new JKApp.KGMWebService.getVerifyCodeByContactsName();
            inValue.Body = new JKApp.KGMWebService.getVerifyCodeByContactsNameBody();
            inValue.Body.verifyCode = verifyCode;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).getVerifyCodeByContactsNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.datacodeOutJsonResponse JKApp.KGMWebService.GmWebServlet.datacodeOutJson(JKApp.KGMWebService.datacodeOutJson request) {
            return base.Channel.datacodeOutJson(request);
        }
        
        public string datacodeOutJson(string base64Code, string TxtNmae) {
            JKApp.KGMWebService.datacodeOutJson inValue = new JKApp.KGMWebService.datacodeOutJson();
            inValue.Body = new JKApp.KGMWebService.datacodeOutJsonBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            JKApp.KGMWebService.datacodeOutJsonResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).datacodeOutJson(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.datacodeOutJsonResponse> JKApp.KGMWebService.GmWebServlet.datacodeOutJsonAsync(JKApp.KGMWebService.datacodeOutJson request) {
            return base.Channel.datacodeOutJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.datacodeOutJsonResponse> datacodeOutJsonAsync(string base64Code, string TxtNmae) {
            JKApp.KGMWebService.datacodeOutJson inValue = new JKApp.KGMWebService.datacodeOutJson();
            inValue.Body = new JKApp.KGMWebService.datacodeOutJsonBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.TxtNmae = TxtNmae;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).datacodeOutJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.saveCardNoResponse JKApp.KGMWebService.GmWebServlet.saveCardNo(JKApp.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNo(request);
        }
        
        public string saveCardNo(string verifyCode, string cardNo) {
            JKApp.KGMWebService.saveCardNo inValue = new JKApp.KGMWebService.saveCardNo();
            inValue.Body = new JKApp.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            JKApp.KGMWebService.saveCardNoResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).saveCardNo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.saveCardNoResponse> JKApp.KGMWebService.GmWebServlet.saveCardNoAsync(JKApp.KGMWebService.saveCardNo request) {
            return base.Channel.saveCardNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.saveCardNoResponse> saveCardNoAsync(string verifyCode, string cardNo) {
            JKApp.KGMWebService.saveCardNo inValue = new JKApp.KGMWebService.saveCardNo();
            inValue.Body = new JKApp.KGMWebService.saveCardNoBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.cardNo = cardNo;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).saveCardNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.isExistOrderResponse JKApp.KGMWebService.GmWebServlet.isExistOrder(JKApp.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrder(request);
        }
        
        public string isExistOrder(string verifyCode, string loginName) {
            JKApp.KGMWebService.isExistOrder inValue = new JKApp.KGMWebService.isExistOrder();
            inValue.Body = new JKApp.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            JKApp.KGMWebService.isExistOrderResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).isExistOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.isExistOrderResponse> JKApp.KGMWebService.GmWebServlet.isExistOrderAsync(JKApp.KGMWebService.isExistOrder request) {
            return base.Channel.isExistOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.isExistOrderResponse> isExistOrderAsync(string verifyCode, string loginName) {
            JKApp.KGMWebService.isExistOrder inValue = new JKApp.KGMWebService.isExistOrder();
            inValue.Body = new JKApp.KGMWebService.isExistOrderBody();
            inValue.Body.verifyCode = verifyCode;
            inValue.Body.loginName = loginName;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).isExistOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.getServiceTimeResponse JKApp.KGMWebService.GmWebServlet.getServiceTime(JKApp.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTime(request);
        }
        
        public string getServiceTime(string cardid) {
            JKApp.KGMWebService.getServiceTime inValue = new JKApp.KGMWebService.getServiceTime();
            inValue.Body = new JKApp.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            JKApp.KGMWebService.getServiceTimeResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).getServiceTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getServiceTimeResponse> JKApp.KGMWebService.GmWebServlet.getServiceTimeAsync(JKApp.KGMWebService.getServiceTime request) {
            return base.Channel.getServiceTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.getServiceTimeResponse> getServiceTimeAsync(string cardid) {
            JKApp.KGMWebService.getServiceTime inValue = new JKApp.KGMWebService.getServiceTime();
            inValue.Body = new JKApp.KGMWebService.getServiceTimeBody();
            inValue.Body.cardid = cardid;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).getServiceTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.getResultResponse JKApp.KGMWebService.GmWebServlet.getResult(JKApp.KGMWebService.getResult request) {
            return base.Channel.getResult(request);
        }
        
        public string getResult(string verifyCode) {
            JKApp.KGMWebService.getResult inValue = new JKApp.KGMWebService.getResult();
            inValue.Body = new JKApp.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            JKApp.KGMWebService.getResultResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).getResult(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getResultResponse> JKApp.KGMWebService.GmWebServlet.getResultAsync(JKApp.KGMWebService.getResult request) {
            return base.Channel.getResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.getResultResponse> getResultAsync(string verifyCode) {
            JKApp.KGMWebService.getResult inValue = new JKApp.KGMWebService.getResult();
            inValue.Body = new JKApp.KGMWebService.getResultBody();
            inValue.Body.verifyCode = verifyCode;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).getResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.getCardNoByOrderResponse JKApp.KGMWebService.GmWebServlet.getCardNoByOrder(JKApp.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrder(request);
        }
        
        public string getCardNoByOrder(string loginName, string cardNo) {
            JKApp.KGMWebService.getCardNoByOrder inValue = new JKApp.KGMWebService.getCardNoByOrder();
            inValue.Body = new JKApp.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            JKApp.KGMWebService.getCardNoByOrderResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).getCardNoByOrder(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.getCardNoByOrderResponse> JKApp.KGMWebService.GmWebServlet.getCardNoByOrderAsync(JKApp.KGMWebService.getCardNoByOrder request) {
            return base.Channel.getCardNoByOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.getCardNoByOrderResponse> getCardNoByOrderAsync(string loginName, string cardNo) {
            JKApp.KGMWebService.getCardNoByOrder inValue = new JKApp.KGMWebService.getCardNoByOrder();
            inValue.Body = new JKApp.KGMWebService.getCardNoByOrderBody();
            inValue.Body.loginName = loginName;
            inValue.Body.cardNo = cardNo;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).getCardNoByOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JKApp.KGMWebService.fileOutXlsResponse JKApp.KGMWebService.GmWebServlet.fileOutXls(JKApp.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXls(request);
        }
        
        public string fileOutXls(string base64Code, string xlsNmae, string orderId, string testDate) {
            JKApp.KGMWebService.fileOutXls inValue = new JKApp.KGMWebService.fileOutXls();
            inValue.Body = new JKApp.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            JKApp.KGMWebService.fileOutXlsResponse retVal = ((JKApp.KGMWebService.GmWebServlet)(this)).fileOutXls(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JKApp.KGMWebService.fileOutXlsResponse> JKApp.KGMWebService.GmWebServlet.fileOutXlsAsync(JKApp.KGMWebService.fileOutXls request) {
            return base.Channel.fileOutXlsAsync(request);
        }
        
        public System.Threading.Tasks.Task<JKApp.KGMWebService.fileOutXlsResponse> fileOutXlsAsync(string base64Code, string xlsNmae, string orderId, string testDate) {
            JKApp.KGMWebService.fileOutXls inValue = new JKApp.KGMWebService.fileOutXls();
            inValue.Body = new JKApp.KGMWebService.fileOutXlsBody();
            inValue.Body.base64Code = base64Code;
            inValue.Body.xlsNmae = xlsNmae;
            inValue.Body.orderId = orderId;
            inValue.Body.testDate = testDate;
            return ((JKApp.KGMWebService.GmWebServlet)(this)).fileOutXlsAsync(inValue);
        }
    }
}
